export const BASE_URL = 'https://trade-plus.in'
export const PATH_URL = '/TradeWebAPI/api/main/tradeweb'
export const LOGIN_URL = '/TradeWebAPI/api/Main/Login_validate_Password'
export const LOGIN_KEY = 'PKQMK2-ZDQS6F-/4UKSQ-QBB3'
export const LOGIN_AS = 'M~2.0.0.1'
export const PRODUCT = 'T'
export const OTP_VERIFICATION_URL = '/TradeWebAPI/api/Main/InitializeLogin'