export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL
export const PATH_URL = process.env.NEXT_PUBLIC_PATH_URL
export const LOGIN_URL = process.env.NEXT_PUBLIC_LOGIN_URL
export const PRODUCT = process.env.NEXT_PUBLIC_PRODUCT
export const OTP_VERIFICATION_URL = process.env.NEXT_PUBLIC_OTP_VERIFICATION_URL
export const APP_METADATA_KEY = process.env.NEXT_PUBLIC_APP_METADATA_KEY;
export const ACTION_NAME = process.env.NEXT_PUBLIC_ACTION_NAME
export const LOGIN_AS_OPTIONS = process.env.NEXT_PUBLIC_LOGIN_AS_OPTIONS
export const LOGIN_KEY = process.env.NEXT_PUBLIC_LOGIN_KEY
export const LOGIN_AS = process.env.NEXT_PUBLIC_LOGIN_AS
export const BASE_PATH_FRONT_END = process.env.NEXT_PUBLIC_BASE_PATH || ''